### ISSUE TITLE
Update runtime to 20.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.phoenicis.playonlinux#10]

**Comment by plata** [comment]
Just had a look at this but it seems that the openjdk extension is not available.

**Comment by plata** [comment]
See https://github.com/PhoenicisOrg/phoenicis/pull/2102. We will update flathub when we release the next version of Phoenicis PlayOnLinux.

**Comment by mbooth101** [comment]
@plata FWIW, runtime 20.08 is now available and runtime 18.08 is facing imminent End-Of-Life.

Any updates on this?

**Comment by plata** [comment]
see https://github.com/PhoenicisOrg/phoenicis/pull/2278
