### ISSUE TITLE
Problem with Epic Games Launcher

### ISSUE THREAD

**Issue by Alvareto136** [flathub/org.phoenicis.playonlinux#12]
Hi, I recently tried to install Epic Games Launcher through Phoenicis but it gave me this error. What can I do in this case?
![Schermata da 2020-06-13 23-37-10](https://user-images.githubusercontent.com/66923863/84604793-2cccce80-ae5e-11ea-96b3-f93bc8d4a767.png)

**Comment by plata** [comment]
This issue should be solved in the next release. Until then, you can download Epic Games Launcher manually and use the Local Installer.
As an alternative, you can built the flatpak based on the latest master version (see https://phoenicisorg.github.io/phoenicis/Developers/packages/).

**Comment by plata** [comment]
If you would like to have a separate flatpak for Epic Games Launcher, try https://github.com/plata/phoenicis-app-flatpak-generator.

**Comment by Alvareto136** [comment]
> This issue should be solved in the next release. Until then, you can download Epic Games Launcher manually and use the Local Installer.
> As an alternative, you can built the flatpak based on the latest master version (see https://phoenicisorg.github.io/phoenicis/Developers/packages/).

Hi, I opened that link but didn't understand how to do it so I went with your second suggestion.

**Comment by Alvareto136** [comment]
Perhaps, I can try your first recommendation:
> As an alternative, you can built the flatpak based on the latest master version (see 
> https://phoenicisorg.github.io/phoenicis/Developers/packages/).

But I don't know what a _phoenicis-dist_ is and I don't know how to install those extensions:
![Schermata da 2020-06-24 13-52-27](https://user-images.githubusercontent.com/66923863/85616867-f3494f80-b623-11ea-91fc-69421b09eed3.png)

Since it's been 6 days and LeandroStranger hasn't responded on the other issue, could you explain me how to do this package thing?

If something my OS is **Endeless 3.8.3**.

Thank you for your assistance up until now, I very much appreciate it.

**Comment by plata** [comment]
You should be able to install Maven from your app store. If you can install OpenJDK as well, you should be able to build Phoenicis.

**Comment by Alvareto136** [comment]
Oh well, this is way too complicated for me, guess it might be better if I just wait for the update 😅

When is the next update coming up?

**Comment by plata** [comment]
Working on it but I cannot promise any ETA.
