### ISSUE TITLE
Adobe acrobat app's Print Dialogue box and Preferences Dialogue box unreadable !!!

### ISSUE THREAD

**Issue by aiamuzz** [flathub/org.phoenicis.playonlinux#3]
Hi,
as you can see i find the following elements unreadable ... is this an Adobe application issue or is it an issue with the flatpak version of the Phoenicis Playonlinux issue or is it a known Phoenicis Playonlinux issue ?

![deepinscreenshot_select-area_20190131212045](https://user-images.githubusercontent.com/3283676/52066279-3eca0c00-259e-11e9-98f2-3902e1676f54.png)
![deepinscreenshot_select-area_20190131212029](https://user-images.githubusercontent.com/3283676/52066280-3eca0c00-259e-11e9-8c55-61682bf06938.png)

**Comment by plata** [comment]
It is not specific for the flatpak. Will move issue to scripts.
